package shopifyapp.kevinli.com.shopifyapp


/**
 * Created by Kevin on 5/8/2018.
 */

data class OrderList(
    val orders: List<Order>
)

data class Order(
    val id: Long,
    val email: String,
    val closed_at: Any,
    val created_at: String,
    val updated_at: String,
    val number: Int,
    val note: Any,
    val token: String,
    val gateway: String,
    val test: Boolean,
    val total_price: String,
    val subtotal_price: String,
    val total_weight: Int,
    val total_tax: String,
    val taxes_included: Boolean,
    val currency: String,
    val financial_status: String,
    val confirmed: Boolean,
    val total_discounts: String,
    val total_line_items_price: String,
    val cart_token: Any,
    val buyer_accepts_marketing: Boolean,
    val name: String,
    val referring_site: Any,
    val landing_site: Any,
    val cancelled_at: Any,
    val cancel_reason: Any,
    val total_price_usd: String,
    val checkout_token: Any,
    val reference: Any,
    val user_id: Any,
    val location_id: Any,
    val source_identifier: Any,
    val source_url: Any,
    val processed_at: String,
    val device_id: Any,
    val phone: Any,
    val customer_locale: Any,
    val app_id: Int,
    val browser_ip: Any,
    val landing_site_ref: Any,
    val order_number: Int,
    val discount_codes: List<Any>,
    val note_attributes: List<Any>,
    val payment_gateway_names: List<String>,
    val processing_method: String,
    val checkout_id: Any,
    val source_name: String,
    val fulfillment_status: Any,
    val tax_lines: List<Any>,
    val tags: String,
    val contact_email: String,
    val order_status_url: String,
    val admin_graphql_api_id: String,
    val line_items: List<LineItem>,
    val shipping_lines: List<Any>,
    val billing_address: BillingAddress,
    val shipping_address: ShippingAddress,
    val fulfillments: List<Any>,
    val refunds: List<Any>,
    val customer: Customer
)

data class Customer(
    val id: Long,
    val email: String,
    val accepts_marketing: Boolean,
    val created_at: String,
    val updated_at: String,
    val first_name: String,
    val last_name: String,
    val orders_count: Int,
    val state: String,
    val total_spent: String,
    val last_order_id: Long,
    val note: Any,
    val verified_email: Boolean,
    val multipass_identifier: Any,
    val tax_exempt: Boolean,
    val phone: Any,
    val tags: String,
    val last_order_name: String,
    val admin_graphql_api_id: String,
    val default_address: DefaultAddress
)

data class DefaultAddress(
    val id: Long,
    val customer_id: Long,
    val first_name: String,
    val last_name: String,
    val company: Any,
    val address1: String,
    val address2: Any,
    val city: String,
    val province: String,
    val country: String,
    val zip: String,
    val phone: String,
    val name: String,
    val province_code: String,
    val country_code: String,
    val country_name: String,
    val default: Boolean
)

data class ShippingAddress(
    val first_name: String,
    val address1: String,
    val phone: String,
    val city: String,
    val zip: String,
    val province: String,
    val country: String,
    val last_name: String,
    val address2: Any,
    val company: Any,
    val latitude: Double,
    val longitude: Double,
    val name: String,
    val country_code: String,
    val province_code: String
)

data class LineItem(
    val id: Long,
    val variant_id: Long,
    val title: String,
    val quantity: Int,
    val price: String,
    val sku: String,
    val variant_title: String,
    val vendor: Any,
    val fulfillment_service: String,
    val product_id: Long,
    val requires_shipping: Boolean,
    val taxable: Boolean,
    val gift_card: Boolean,
    val name: String,
    val variant_inventory_management: Any,
    val properties: List<Any>,
    val product_exists: Boolean,
    val fulfillable_quantity: Int,
    val grams: Int,
    val total_discount: String,
    val fulfillment_status: Any,
    val admin_graphql_api_id: String,
    val tax_lines: List<Any>
)

data class BillingAddress(
    val first_name: String,
    val address1: String,
    val phone: String,
    val city: String,
    val zip: String,
    val province: String,
    val country: String,
    val last_name: String,
    val address2: Any,
    val company: Any,
    val latitude: Double,
    val longitude: Double,
    val name: String,
    val country_code: String,
    val province_code: String
)